// Generated by https://quicktype.io

export interface LoginAPI {
  id: string
  name: string
  email: string
  online: boolean
  token: string
}

export interface MessageAPI {
  id: string
  message: string
  created_at: string
  author: Author
  destination: Author
}

export interface Author {
  id: string
  name: string
  email: string
  password: string
  online: boolean
}
